name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clone Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
        run: |
          git clone https://oauth2:${HF_TOKEN}@huggingface.co/spaces/${HF_USERNAME}/Telegram_Bot hf-space

      - name: Clean Space
        run: |
          find hf-space -mindepth 1 -maxdepth 1 ! -name ".git" -exec rm -rf {} +

      - name: Copy Backend
        run: |
          cp Dockerfile hf-space/
          cp go.mod hf-space/
          cp README.md hf-space/ || true

          cp -r backend hf-space/ || true
          cp -r cmd hf-space/ || true

      - name: Commit & Push
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
        run: |
          cd hf-space

          git add .

          git commit -m "Auto Deploy $(date)" || true

          git push https://oauth2:${HF_TOKEN}@huggingface.co/spaces/${HF_USERNAME}/Telegram_Bot main
