name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clone Hugging Face Space
        run: |
          git clone https://oauth2:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ secrets.HF_USERNAME }}/Telegram_Bot space

      - name: Copy project
        run: |
          rsync -av --delete --exclude ".git" ./ space/

      - name: Push to Hugging Face
        run: |
          cd space
          git add .
          git commit -m "Auto Deploy from GitHub" || echo "No changes"
          git push https://oauth2:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ secrets.HF_USERNAME }}/Telegram_Bot
